### ISSUE TITLE
Deployment – Test interLink SLURM plugin

### ISSUE THREAD

**Issue by tranchis** [aiondemand/AIOD-HPC-Autolauncher#2]
* Check documentation of interLink and its SLURM plugin:
  * https://github.com/interlink-hq/interLink
  * https://github.com/interlink-hq/interlink-slurm-plugin
* Deploy interLink-enabled pod in k8s
* Use already deployed SLURM machine in Openstack
* Do a quick test using any simple script

**Comment by oriolmirolf** [comment]
Completed! 🥳 Proved quite troublesome, so I will leave a detailed guide (now that it's fresh) in case it needs replication.

---

### What I needed: 
* Docs used:
- interLink core – [https://github.com/interlink-hq/interLink](https://github.com/interlink-hq/interLink)
- SLURM sidecar plugin – [https://github.com/interlink-hq/interlink-slurm-plugin](https://github.com/interlink-hq/interlink-slurm-plugin)
- Edge cookbook – [https://interlink-project.dev/docs/cookbook/edge](https://interlink-project.dev/docs/cookbook/edge)

* **Environment**
(all in openstack)

  * Kubernetes (v1.30.14):

    * `k8-test-master` – 192.168.0.249
    * `k8-test-worker` – 192.168.0.152
  * SLURM single-node (Ubuntu 24.04):

    * `slurm-test` – 192.168.0.224 (2 vCPU / 8 GiB RAM)
  * interLink Helm chart: **0.5.2** (OCI)
  * interLink API (remote VM): **0.5.1** (installer)
  * Virtual Kubelet: **0.5.2-pre2**

---

### Final working version details (edge mode)

#### 1) Remote (on the SLURM VM)

**interLink installer config** (`~/.interlink/installer.yaml`) (i used no auth for quick test! oauth:{}):

```yaml
interlink_ip: 0.0.0.0
interlink_port: 30433
interlink_version: "0.5.1"
kubelet_node_name: slurm-edge
kubernetes_namespace: interlink
node_limits: { cpu: "2000", memory: "6144", pods: "10" }  # 2 vCPU, 6 GiB
oauth: {}
insecure_http: true
```

Generate scripts & config, then start the API:

```bash
~/.interlink/interlink-installer --config ~/.interlink/installer.yaml --output-dir ~/.interlink/manifests/
chmod +x ~/.interlink/manifests/interlink-remote.sh
~/.interlink/manifests/interlink-remote.sh install
~/.interlink/manifests/interlink-remote.sh start
```

**SLURM sidecar plugin** (`~/.interlink/manifests/plugin-config.yaml`):

```yaml
Socket: "unix:///home/ubuntu/.interlink/.plugin.sock"
DataRootFolder: "/home/ubuntu/.interlink/jobs/"
SbatchPath: "/usr/bin/sbatch"
ScancelPath: "/usr/bin/scancel"
SqueuePath: "/usr/bin/squeue"
ImagePrefix: "docker://"
VerboseLogging: true
```

Run plugin (and then made it persistent via systemd below):

```bash
export SLURMCONFIGPATH=$HOME/.interlink/manifests/plugin-config.yaml
nohup ~/.interlink/bin/interlink-slurm-plugin > ~/.interlink/logs/plugin.log 2>&1 &
```

**Expose the API UNIX socket to TCP 30433** (no-auth PoC):

```bash
sudo apt install -y socat
sudo nohup socat TCP-LISTEN:30433,fork,bind=0.0.0.0 UNIX-CONNECT:$HOME/.interlink/.interlink.sock \
  > $HOME/.interlink/logs/socat.log 2>&1 &
```

**Container runtime on SLURM node:** installed **SingularityCE** from Ubuntu (package `singularity-container`) and deps:

```bash
sudo add-apt-repository -y universe
sudo apt update
sudo apt --fix-broken install -y
sudo apt install -y singularity-container containernetworking-plugins uidmap fuse-overlayfs squashfuse
singularity exec docker://busybox:1.36 true
```

> For persistence, I added two systemd units:
>
> * `interlink-slurm-plugin.service` (removes stale `.plugin.sock` before start)
> * `interlink-api-bridge.service` (waits for `.interlink.sock`, then runs `socat`)

Units used:

```ini
# /etc/systemd/system/interlink-slurm-plugin.service
[Unit]
Description=interLink SLURM sidecar plugin
After=network-online.target munge.service
Wants=network-online.target
[Service]
User=ubuntu
WorkingDirectory=/home/ubuntu
Environment=SLURMCONFIGPATH=/home/ubuntu/.interlink/manifests/plugin-config.yaml
ExecStartPre=/bin/rm -f /home/ubuntu/.interlink/.plugin.sock
ExecStart=/home/ubuntu/.interlink/bin/interlink-slurm-plugin
Restart=on-failure
RestartSec=2
[Install]
WantedBy=multi-user.target
```

```ini
# /etc/systemd/system/interlink-api-bridge.service
[Unit]
Description=Expose interLink UNIX socket on TCP 30433
After=network-online.target
Wants=network-online.target
[Service]
User=ubuntu
ExecStartPre=/bin/sh -c 'for i in $(seq 1 60); do [ -S /home/ubuntu/.interlink/.interlink.sock ] && exit 0; sleep 1; done; exit 1'
ExecStart=/usr/bin/socat TCP-LISTEN:30433,fork,bind=0.0.0.0 UNIX-CONNECT:/home/ubuntu/.interlink/.interlink.sock
Restart=always
RestartSec=1
[Install]
WantedBy=multi-user.target
```

Checking everything is reachable from K8s master:

```bash
curl -v http://192.168.0.224:30433/pinglink
# returns HTTP/200 with SLURM sinfo summary
```

---

#### 2) Kubernetes (on the cluster)

Helm chart (OCI) + minimal values to point to the remote API and disable OAuth:

```bash
export CHART=oci://ghcr.io/interlink-hq/interlink-helm-chart/interlink
export CHART_VER=0.5.2
cat >/tmp/interlink-values.yaml <<'EOF'
nodeName: slurm-edge
interlink:
  address: http://192.168.0.224
  port: 30433
OAUTH:
  enabled: false
virtualNode:
  resources: { CPUs: 2, memGiB: 6, pods: 10 }
EOF

helm upgrade --install -n interlink --create-namespace slurm-edge $CHART \
  --version "$CHART_VER" --values /tmp/interlink-values.yaml
```

We previously patched the VK to use `hostNetwork`; that collided with the host kubelet on `10250`. Fix: set VK to listen on a different port:

```bash
kubectl -n interlink set env deploy/slurm-edge-node KUBELET_PORT=20250
kubectl -n interlink rollout status deploy/slurm-edge-node
```

Node appears and becomes **Ready**:

```bash
kubectl get nodes
# shows: slurm-edge   Ready   agent   ...   0.5.2-pre2
```

---

### Test run (works!!)

Simple pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: hello-slurm
  namespace: interlink
spec:
  nodeSelector:
    kubernetes.io/hostname: slurm-edge
  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
  restartPolicy: Never
  containers:
  - name: hello
    image: busybox:1.36             # plugin auto-prefixes "docker://"
    command: ["sh","-c","echo $(hostname); echo OK && sleep 3"]
    resources:
      requests: { cpu: "250m", memory: "128Mi" }
      limits:   { cpu: "500m", memory: "256Mi" }
```

Result:

* Pod transitions **Pending → Running → Completed**.
* Logs show:

  ```
  Using cached SIF image
  slurm-test
  OK
  ```
* On the SLURM node, `squeue -u <user>` shows the transient job while the pod runs.

---

### (many) issues hit & how we solved them

* **SLURM:** `scontrol update … : Invalid user id`
  --> Run admin commands with `sudo`. `AdminUsers` is removed in recent Slurm; full role management now requires slurmdbd. For this PoC we kept `AccountingStorageType=none` and used `sudo`.

* **Helm chart 404** when using the GitHub repo URL
  --> Use the **OCI** registry path: `oci://ghcr.io/interlink-hq/interlink-helm-chart/interlink` (v0.5.2).

* **VK CrashLoop**: `open /opt/interlink/token: no such file or directory`
  --> Default values enabled OAuth; we set `OAUTH.enabled: false`.

* **Remote API unreachable** (`curl …:30433 → connection refused`)
  --> Installer started API on **UNIX socket only**; we exposed it via **socat** on TCP 30433. Also cleaned stale socket and ensured the **plugin** was running; otherwise `/pinglink` returns 503.

* **VK bind error**: `listen tcp 0.0.0.0:10250: bind: address already in use`
  --> Due to `hostNetwork: true`. Set `KUBELET_PORT=20250` for VK.

* **Pod exit 127**: `singularity: command not found`
  --> Install **SingularityCE** (`singularity-container`) and deps on the SLURM node; optionally set `ImagePrefix: "docker://"` in plugin config.

* **systemd flaps** for plugin/bridge
  --> Add `ExecStartPre` to remove stale socket for plugin; make the bridge **wait** for the API socket; both are stable now.
