### ISSUE TITLE
Deployment – Test AI pipeline that depends on SLURM step

### ISSUE THREAD

**Issue by tranchis** [aiondemand/AIOD-HPC-Autolauncher#3]

**Comment by oriolmirolf** [comment]
Done! 🥳 
---

### Setup 
(as with [previous issue](https://github.com/aiondemand/AIOD-HPC-Autolauncher/issues/2))

* **SLURM VM** (`slurm-test`, Ubuntu 24.04) runs:

  * `interlink` (remote API) on UNIX socket, exposed at TCP 30433 via `socat`.
  * interlink-slurm-plugin (sidecar) active.
* **Kubernetes** (1.30.14) has Virtual Kubelet ("slurm-edge") from helm chart `interlink-helm-chart:0.5.2`, OAuth disabled.
* **Virtual node** shows `Ready` and schedules pods to the SLURM VM.

---

### ML validation job

A CPU-only Iris pipeline (no CV), using a HostPath volume so `pip` writes to disk and not the Singularity overlay.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: autolaunch-iris-fast
  namespace: interlink
spec:
  template:
    spec:
      nodeSelector: { kubernetes.io/hostname: slurm-edge }
      tolerations:
        - key: virtual-node.interlink/no-schedule
          operator: Exists
      restartPolicy: Never
      containers:
        - name: trainer
          image: python:3.11-slim
          volumeMounts: [{ name: work, mountPath: /work }]
          env:
            - { name: HOME, value: /work }
            - { name: TMPDIR, value: /work/tmp }
            - { name: PIP_CACHE_DIR, value: /work/pip }
          command: ["sh","-lc"]
          args:
            - |
              set -ex
              PKGDIR="/work/pkgs-iris"; mkdir -p "$PKGDIR"
              python -m pip install --no-cache-dir -t "$PKGDIR" \
                numpy==2.0.1 scipy==1.16.1 scikit-learn==1.5.1
              export PYTHONPATH="${PKGDIR}:${PYTHONPATH:-}"
              python - <<'PY'
              from sklearn.datasets import load_iris
              from sklearn.model_selection import train_test_split
              from sklearn.preprocessing import StandardScaler
              from sklearn.linear_model import LogisticRegression
              from sklearn.pipeline import make_pipeline
              from sklearn.metrics import accuracy_score
              X,y = load_iris(return_X_y=True)
              Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)
              model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=500))
              model.fit(Xtr,ytr)
              print("iris_test_accuracy=", round(accuracy_score(yte, model.predict(Xte)),3))
              PY
          resources:
            requests: { cpu: "500m", memory: "512Mi" }
            limits:   { cpu: "1",    memory: "1Gi" }
      volumes:
        - name: work
          hostPath: { path: /home/ubuntu/.interlink/work, type: DirectoryOrCreate }
```

**Result (logs):**

```
iris_test_accuracy= 0.933
Pod: Completed (exit code 0)
```

---

### Notes
* Exposed interLink UNIX socket via `socat` on **30433** so VK could reach it.
* Avoided first-time `pip` “no space left on device” by binding **HostPath → /work** (disk-backed write).
* Set VK `KUBELET_PORT=20250` to avoid local port conflicts.
* OAuth left **disabled** for this quick test.
